### ISSUE TITLE
Add a Natural Earth v4 quick-start style

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola-osm#12]
Add a style that uses only Natural Earth v 4 data. The style can use the same/similar design as the QGIS and ArcMap quickstart styles. Example:

![nequickstart](https://user-images.githubusercontent.com/5266205/32454297-10f11100-c2dc-11e7-8607-9e5a0a5e26ce.PNG)

**Comment by PetersonGIS** [comment]
The style is working locally. But we are missing some layers in the database.
local render screenshots

![natearth4](https://user-images.githubusercontent.com/5266205/34491130-75b212a2-ef9f-11e7-927e-8e44597edbde.PNG)

![natearth3](https://user-images.githubusercontent.com/5266205/34491132-7909023a-ef9f-11e7-804a-bb48f07ae8d3.PNG)


We need to update the data import list.
:

**Comment by ARolek** [comment]
data has been deployed and so has the new config.
