### ISSUE TITLE
Fix state_lines in night-vision

### ISSUE THREAD

**Issue by jj0hns0n** [go-spatial/tegola-osm#2]
<img width="967" alt="screen shot 2017-11-02 at 13 39 16" src="https://user-images.githubusercontent.com/506078/32349118-444b24f2-bfd3-11e7-8c19-0830ed85a611.png">

**Comment by ARolek** [comment]
@PetersonGIS any idea when this one will be addressed?

**Comment by PetersonGIS** [comment]
Two ways to fix this:
1) I can simply remove the state_lines reference in the style
2) We can fix the state_lines data by re-adding it to the toml and reimporting (it was commented out of the toml at one point because it wasn't loading properly, and now I believe it has been removed altogether)

**Comment by PetersonGIS** [comment]
Fixed via method 1 above. At some point we need to re-add state_lines to the data though.
