### ISSUE TITLE
error fetching geometry type for layer (land_0-9): ERROR: relation "simplified_land_polygons" does not exist (SQLSTATE 42P01)

### ISSUE THREAD

**Issue by erictheise** [go-spatial/tegola-osm#22]
v0.4.0-rc2.  Just following steps in the README.

**Comment by ARolek** [comment]
@erictheise did you bring in the Natural Earth dataset?

**Comment by erictheise** [comment]
I suspected that was the problem but I'm only interested in OSM and the README says

> Import the Natural Earth dataset (requires gdal. can be skipped if you're only interested in OSM)

Perhaps the meaning of "interested in OSM" should be spelled out?

**Comment by erictheise** [comment]
Appears that in addition to running `natural_earth.sh` you also need to run the undocumented `osm_land.sh` script for this to have any chance of working.

**Comment by ARolek** [comment]
@erictheise good point. maybe we need a few different tegola.toml files for the various combinations. i.e. `tegola-natural-earth.toml`, `tegola-osm.toml`, `tegola-osm-natural-earth.toml`

**Comment by ARolek** [comment]
I updated the readme file to mention running the `osm_land.sh` file. I'm going to close this issue for now. I think we can spin up a different issue for the various config files. @PetersonGIS is already working on updating them for Natural Earth v4.
