### ISSUE TITLE
Fix issues with setLayerProperty, setLayerProperty, setSprite etc

### ISSUE THREAD

**Issue by jj0hns0n** [go-spatial/tegola-osm#3]
This is causing the tiles to be re-requested and redrawn when switching styles.
<img width="973" alt="screen shot 2017-11-02 at 13 40 30" src="https://user-images.githubusercontent.com/506078/32349173-68a50f84-bfd3-11e7-8bb2-81e39f2715b0.png">

**Comment by ARolek** [comment]
@jj0hns0n I'm going to migrate this to the go-spatial/tegola-web-demo repo.
