### ISSUE TITLE
Missing Nepal

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola-osm#32]
Oddly we seem to be missing Nepal from ne_50m_admin_0_boundary_lines_land. It is not missing from our ne_10m nor our ne_110m downloads. The original file from Natural Earth does have it, as verified in qgis.

![nepal](https://user-images.githubusercontent.com/5266205/33785086-cf274556-dc20-11e7-9121-b699c38d1fbd.PNG)

**Comment by PetersonGIS** [comment]
Here is what the corresponding Natural Earth shapefile looks like in QGIS, with Nepal highlighted:
![nepal2](https://user-images.githubusercontent.com/5266205/33788787-5b092958-dc31-11e7-90ac-851f00f0c751.PNG)

Without highlight:
![nepal3](https://user-images.githubusercontent.com/5266205/33788809-89e706a0-dc31-11e7-80f4-450522768d95.PNG)

**Comment by PetersonGIS** [comment]
This seems like it is fixed in v0.6.1 (tested locally). Can we try clearing the cache in demo.tegola.io for zooms 3 and 4 to see if that fixes this there?

**Comment by erictheise** [comment]
I'm doing some work on the server right now and this fits right in.

**Comment by erictheise** [comment]
@PetersonGIS, I've installed v0.6.1 for the osm/demo project and regenerated the zoom level 3 & 4 tiles but don't see any difference. The data you're looking at is pulled from the server or a local copy?

**Comment by PetersonGIS** [comment]
Interesting. I was pulling from a local copy, which was originally from that data though. I'll dig deeper to further look at the data differences as well as the toml and json differences that there might be between my local setup and what's on the demo.

**Comment by erictheise** [comment]
My suspicion would be that there's a difference in the `.toml`. Nepal is in `_disputed`?

**Comment by PetersonGIS** [comment]
I was wrong, it isn't fixed locally. I was looking at ne.ne_50m_admin_0_countries rather than ne_50m_admin_0_boundary_lines_land. Nepal is still missing in ne_50m_admin_0_boundary_lines_land when served by tegola but not missing if we look at ne_50m_admin_0_boundary_lines_land in qgis.

**Comment by PetersonGIS** [comment]
Verified there are 361 rows in ne_50m_admin_0_boundary_lines_land as reported in both qgis and local natural earth db. Suspect 361 in our ne cloud db too. So something is making it not render though it is there in the db? It is a fully enclosed line, does that make a difference to the renderer?

**Comment by PetersonGIS** [comment]
Missing these fully enclosed lines in the ne_50m_admin_0_boundary_lines_land data too.

![enclosedlines2](https://user-images.githubusercontent.com/5266205/36919534-e51900b6-1e1a-11e8-8811-ddc61795db40.JPG)

**Comment by ARolek** [comment]
@PetersonGIS turn simplification off for that layer locally. I have a feeling that polygon is getting removed during simplification. Simplification might not be necessary for those layers too since they're already simplified.

**Comment by PetersonGIS** [comment]
@ARolek that was the solution!

`[[maps.layers]]
	name = "boundary_lines_land"
	provider_layer = "ne.ne_50m_admin_0_boundary_lines_land"
	dont_simplify = true
	min_zoom = 3
	max_zoom = 4`

**Comment by ARolek** [comment]
@PetersonGIS beautiful! PR has been merged. Time to close this one out ;-)
