### ISSUE TITLE
land_polygons layer creates "broken" tiles?

### ISSUE THREAD

**Issue by jkempe** [go-spatial/tegola-osm#39]
I have noted issues with the layer land at zoom levels higher than 8, when we switch to osm.land_polygons. Tiles generated looks like the lack one corner of each split polygon. The problem is visible here:

![image](https://user-images.githubusercontent.com/5214337/36102158-c362feee-100b-11e8-951f-9f22da44a71d.png)

I see the issue on both my instance (v0.5.0) and on osm.tegola.io

**Comment by ARolek** [comment]
@jkempe this is a simplification bug we're working on. The Douglas Packard algo does not play nicely nicely with right angles at that tolerance. A few issues / options to try / watch

- Turn off simplification: Check out `DontSimplifyGeo` under https://github.com/terranodo/tegola#environment-variables
- [Plumb through simplification parameter to the config file](https://github.com/terranodo/tegola/issues/165)
- [Change out the simplification algorithm](https://github.com/terranodo/tegola/issues/166)

The last bullet will hopefully produce the best results. Additionally you can turn off simplification after a certain zoom using the env vars in the first bullet. That's another near term option.

**Comment by ARolek** [comment]
This is now fixable using tegola v0.6.1 and setting `dont_simplify = true` on the following part of the config (updated in this repo):

```toml
[[maps.layers]]
name = "land"
provider_layer = "osm.land_8-20"
dont_simplify = true
min_zoom = 8
max_zoom = 20
```
