### ISSUE TITLE
Update server binary to just-released v0.6.0

### ISSUE THREAD

**Issue by erictheise** [go-spatial/tegola-osm#42]
Replace Tegola v0.5.0 with v0.6.0 on the public-facing server. Use environment variables, available in this release, to configure the app in production and update related files here in the repo.

**Comment by ARolek** [comment]
@erictheise any reason to leave this issue open?

**Comment by erictheise** [comment]
Left this open until configs were standardized in production. That's done, we're running v0.6.2 on the public facing instances, closing this booger.
