### ISSUE TITLE
Relation does not exist

### ISSUE THREAD

**Issue by MrSatan** [go-spatial/tegola-osm#63]
i followed instruction  , when trying to index the new shape included via land.sh i get this error

```
 psql -d tegola -a -f postgis_index.sql
/*
        Adds indexes to OSM table columns to increase query performance per the tegola configuration.
*/
BEGIN;
BEGIN
        CREATE INDEX ON osm_transport_lines_gen0 (type);
psql:postgis_index.sql:6: ERROR:  relation "osm_transport_lines_gen0" does not exist
        CREATE INDEX ON osm_transport_lines_gen1 (type);
psql:postgis_index.sql:7: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_transport_lines (type);
psql:postgis_index.sql:8: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_admin_areas (admin_level);
psql:postgis_index.sql:9: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_landuse_areas_gen0 (type);
psql:postgis_index.sql:10: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_lines (type);
psql:postgis_index.sql:11: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_lines_gen0 (type);
psql:postgis_index.sql:12: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_lines_gen1 (type);
psql:postgis_index.sql:13: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_areas (type);
psql:postgis_index.sql:14: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_areas_gen0 (type);
psql:postgis_index.sql:15: ERROR:  current transaction is aborted, commands ignored until end of transaction block
        CREATE INDEX ON osm_water_areas_gen1 (type);
psql:postgis_index.sql:16: ERROR:  current transaction is aborted, commands ignored until end of transaction block
COMMIT;
ROLLBACK
```
i tried to manually downlaod the file and import the shape using ogr but still those relations are not created . 
when i run the map i receive no table for osm staff

**Comment by MrSatan** [comment]
[Oct 20 14:48:51] [PostGIS] Rotating osm_water_lines from import -> public -> backup
[Oct 20 14:48:51] [PostGIS] backup of osm_water_lines, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_transport_points from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_transport_points, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_buildings from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_buildings, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_admin_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_admin_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_other_lines from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_other_lines, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_transport_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_transport_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_water_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_water_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_place_points from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_place_points, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_other_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_other_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_amenity_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_amenity_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_transport_lines from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_transport_lines, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_landuse_areas from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_landuse_areas, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_other_points from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_other_points, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_amenity_points from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] backup of osm_amenity_points, to backup
[Oct 20 14:48:52] [PostGIS] Rotating osm_water_areas_gen1 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_water_areas_gen1, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_water_areas_gen0 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_water_areas_gen0, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_transport_lines_gen0 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_transport_lines_gen0, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_transport_lines_gen1 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_transport_lines_gen1, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_water_lines_gen0 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_water_lines_gen0, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_water_lines_gen1 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_water_lines_gen1, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_landuse_areas_gen1 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_landuse_areas_gen1, table does not exists in import
[Oct 20 14:48:52] [PostGIS] Rotating osm_landuse_areas_gen0 from import -> public -> backup
[Oct 20 14:48:52] [PostGIS] skipping rotate of osm_landuse_areas_gen0, table does not exists in import

**Comment by ARolek** [comment]
When you ran `imposm` did you use the `-deployproduction` flag? The following line in the errors log has me thinking you might not have the data in the public schema: `psql:postgis_index.sql:6: ERROR:  relation "osm_transport_lines_gen0" does not exist`

**Comment by MrSatan** [comment]
thanks for reponsing . i find out what was the problem , i had downloaded old version of imposm3(few years ago release).

**Comment by ARolek** [comment]
Regarding the style sheet, take a look at https://fresco.gospatial.org/. it will auto generate a default style for you.

**Comment by MrSatan** [comment]
> 
> 
> Regarding the style sheet, take a look at https://fresco.gospatial.org/. it will auto generate a default style for you.

Thank you . unfurtonatly i have one option to render map in android which is VTM that dosent support mapbox style. 
i couldnt setup my vector map in mapbox i didnt find any instruction about it
